export const batch_nature = [
  { word: 'AGUAS', difficulty: 'common', tags: ['nature'] },
  { word: 'ALAMO', difficulty: 'medium', tags: ['nature'] },
  { word: 'AMBAR', difficulty: 'medium', tags: ['nature', 'object'] },
  { word: 'ANGRA', difficulty: 'rare', tags: ['place', 'nature'] },
  { word: 'ANTRO', difficulty: 'medium', tags: ['place', 'nature'] },
  { word: 'ARENA', difficulty: 'common', tags: ['nature', 'place'] },
  { word: 'ARIDA', difficulty: 'common', tags: ['descriptor', 'nature'] },
  { word: 'AROMA', difficulty: 'common', tags: ['descriptor', 'nature'] },
  { word: 'ARROZ', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'AVEIA', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'BACIA', difficulty: 'common', tags: ['nature', 'place', 'object'] },
  { word: 'BAMBU', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'BARRA', difficulty: 'common', tags: ['place', 'nature'] },
  { word: 'BASAL', difficulty: 'rare', tags: ['descriptor', 'nature'] },
  { word: 'BEIRA', difficulty: 'common', tags: ['place', 'nature'] },
  { word: 'BERCO', difficulty: 'common', tags: ['place', 'nature'] },
  { word: 'BIOTA', difficulty: 'rare', tags: ['nature'] },
  { word: 'BISAO', difficulty: 'medium', tags: ['animal', 'nature'] },
  { word: 'BOLHA', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'BORDA', difficulty: 'common', tags: ['place', 'nature'] },
  { word: 'BORRA', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'BOTAO', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'BREJO', difficulty: 'common', tags: ['place', 'nature'] },
  { word: 'BURRO', difficulty: 'common', tags: ['animal', 'nature'] },
  { word: 'CACAU', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'CALHA', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'CANOA', difficulty: 'common', tags: ['object', 'nature'] },
  { word: 'CAOBA', difficulty: 'medium', tags: ['nature', 'object'] },
  { word: 'CAUDA', difficulty: 'common', tags: ['animal', 'nature'] },
  { word: 'CAULE', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'CEIFA', difficulty: 'common', tags: ['action', 'nature'] },
  { word: 'CERNE', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'CERVO', difficulty: 'common', tags: ['animal', 'nature'] },
  { word: 'CESIO', difficulty: 'rare', tags: ['nature', 'object'] },
  { word: 'CHAMA', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'CHEIA', difficulty: 'common', tags: ['nature'] },
  { word: 'CICLO', difficulty: 'common', tags: ['time', 'nature'] },
  { word: 'CINZA', difficulty: 'common', tags: ['descriptor', 'nature', 'object'] },
  { word: 'CISCO', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'COSMO', difficulty: 'common', tags: ['nature', 'place'] },
  { word: 'COURO', difficulty: 'common', tags: ['animal', 'nature', 'object'] },
  { word: 'COUVE', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'CUIAS', difficulty: 'rare', tags: ['nature', 'object'] },
  { word: 'DELTA', difficulty: 'common', tags: ['place', 'nature'] },
  { word: 'DENSO', difficulty: 'common', tags: ['descriptor', 'nature'] },
  { word: 'EBANO', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'ERICA', difficulty: 'rare', tags: ['nature'] },
  { word: 'EROSO', difficulty: 'rare', tags: ['descriptor', 'nature'] },
  { word: 'ESTIO', difficulty: 'common', tags: ['time', 'nature'] },
  { word: 'FENDA', difficulty: 'medium', tags: ['place', 'nature'] },
  { word: 'FERVE', difficulty: 'medium', tags: ['action', 'nature'] },
  { word: 'FICUS', difficulty: 'medium', tags: ['nature'] },
  { word: 'FINCA', difficulty: 'medium', tags: ['place', 'nature'] },
  { word: 'FLOCO', difficulty: 'medium', tags: ['nature', 'object'] },
  { word: 'FOLHA', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'FONTE', difficulty: 'common', tags: ['place', 'nature', 'object'] },
  { word: 'FOSSO', difficulty: 'common', tags: ['place', 'nature'] },
  { word: 'FRUTO', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'FUNGO', difficulty: 'common', tags: ['nature'] },
  { word: 'GANSO', difficulty: 'common', tags: ['animal', 'nature'] },
  { word: 'GEMAS', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'GESSO', difficulty: 'common', tags: ['nature', 'object'] },
  { word: 'GLEBA', difficulty: 'medium', tags: ['place', 'nature'] },
  { word: 'GLOBO', difficulty: 'common', tags: ['object', 'nature'] },
  { word: 'GOSMA', difficulty: 'medium', tags: ['nature', 'object'] },
  { word: 'HELIO', difficulty: 'medium', tags: ['nature', 'object'] },
  { word: 'IGNEO', difficulty: 'rare', tags: ['descriptor', 'nature'] },
  { word: 'LAMAS', difficulty: 'common', tags: ['nature'] },
  { word: 'MARE', difficulty: 'common', tags: ['nature'] },
  { word: 'MATA', difficulty: 'common', tags: ['nature'] },
  { word: 'NINHO', difficulty: 'common', tags: ['animal'] },
  { word: 'NORMA', difficulty: 'common', tags: ['social'] },
  { word: 'NUVEM', difficulty: 'common', tags: ['nature'] },
  { word: 'PEDRA', difficulty: 'common', tags: ['nature'] },
  { word: 'PLANTA', difficulty: 'common', tags: ['nature'] },
  { word: 'PRADO', difficulty: 'common', tags: ['nature', 'place'] },
  { word: 'REGA', difficulty: 'common', tags: ['action', 'nature'] },
  { word: 'RIOS', difficulty: 'common', tags: ['nature'] },
  { word: 'SAL', difficulty: 'common', tags: ['nature'] },
  { word: 'SECA', difficulty: 'common', tags: ['nature', 'descriptor'] },
  { word: 'SELO', difficulty: 'common', tags: ['object'] },
  { word: 'SEXO', difficulty: 'common', tags: ['people'] },
  { word: 'SIRI', difficulty: 'common', tags: ['animal'] },
  { word: 'SOLO', difficulty: 'common', tags: ['nature'] },
  { word: 'TETO', difficulty: 'common', tags: ['place'] },
  { word: 'TIO', difficulty: 'common', tags: ['people'] },
  { word: 'VASO', difficulty: 'common', tags: ['object'] },
  { word: 'VIDA', difficulty: 'common', tags: ['people'] },
  { word: 'VIDRO', difficulty: 'common', tags: ['object'] },
  { word: 'VILA', difficulty: 'common', tags: ['place'] },
  { word: 'VINHO', difficulty: 'common', tags: ['object'] },
  { word: 'ZINCO', difficulty: 'rare', tags: ['nature'] },
];